version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todolist-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ThisIs_a_StrongP@ssw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - todolist-network

  api:
    container_name: todolist-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=TodoListDb;User ID=sa;Password=ThisIs_a_StrongP@ssw0rd;TrustServerCertificate=True;"
      # OpenTelemetry configuration will export to console only
      OpenTelemetry__ServiceName: "TodoList.API"
      OpenTelemetry__ServiceVersion: "1.0.0"
    depends_on:
      - db
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge

volumes:
  sqlserver_data: 